jira:
  projectKey: "BOOKKEEPER"

github:
  repository: "bookkeeper"
  owner: "apache"
  branch: "main"
  #localClonePath: "/path/to/my/project/clone" # Optional: specify if you want to use a local clone

output:
  directory: "reports"